# Generated by Django 4.2.3 on 2023-07-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_request', '0004_rename_friend_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
